name: Test

on:
  workflow_call:
    inputs:
      enable_pr_comment:
        description: 'Enable PR comment'
        required: false
        default: true
        type: 'boolean'

permissions:
  contents: read
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - id: test
        name: Run tests
        continue-on-error: true
        run: |
          npm test || echo "status=$?" >> $GITHUB_OUTPUT
      - name: debug
        run: |
          echo "status: ${{ steps.test.outputs.status }}"
          echo "enable_pr_comment: ${{ inputs.enable_pr_comment }}"
      - name: Create comment file
        if: ${{ steps.test.outputs.status != 0 && inputs.enable_pr_comment == true }}
        run: |
          cat  << EOF > comment.md
          ## Test Failed
          The tests failed. Please check the logs for more information.
          https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}
          EOF
      - name: Create PR comment
        if: ${{ steps.test.outputs.status != 0 && inputs.enable_pr_comment == true }}
        run: |
          gh pr comment ${{ github.event.number }} --body-file comment.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}