name: Check Pull Request

on:
  pull_request:
    branches:
      - master

permissions:
  contents: read
  pull-requests: write

jobs:
  put-comment-test:
    uses: ./.github/workflows/test.yml
    with:
      enable_pr_comment: true
    permissions:
      contents: read
      pull-requests: write
  not-comment-test:
    uses: ./.github/workflows/test.yml
    with:
      enable_pr_comment: false
    permissions:
      contents: read
      pull-requests: write